### ISSUE TITLE
Error parsing message

### ISSUE THREAD

**Issue by WeiYangBin** [crownpku/Chinese-VQA#3]
```
Traceback (most recent call last):
  File "/Users/weiyangbin/Chinese-VQA/extract_fc7.py", line 101, in <module>
    main()
  File "/Users/weiyangbin/Chinese-VQA/extract_fc7.py", line 34, in main
    graph_def.ParseFromString(vgg16raw)
google.protobuf.message.DecodeError: Error parsing message
```
您好，我下载了**vgg16_weights.npz** 文件，放在了‘Data/Data/vgg16-Data/vgg16-2016Data/vgg16-2016129.Data/vgg16-2016129.tfData/vgg16-2016129.tfmodel.torretorrent/’下
但是但我运行 **extract_fc.py**文件时却发生以上错误。

且源代码29行
```
vgg_file = open(args.model_path)
```
如不加‘rb’
```
vgg_file = open(args.model_path,'rb')
```
也会报如下错误
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 12: invalid continuation byte
```

**Comment by WeiYangBin** [comment]
已经解决，下载 ***.tfmodel*** 文件

**Comment by Xu-Fengnian** [comment]
> 已经解决，下载 _**.tfmodel**_ 文件

请问在哪里下载

**Comment by WeiYangBin** [comment]
> > 已经解决，下载 _**.tfmodel**_ 文件
> 
> 请问在哪里下载

[下载地址](https://github.com/ry/tensorflow-vgg16)
